name: Publish Pages via GH CLI

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Setup Pages via GH CLI"

# Allow one concurrent deployment
concurrency:
  group: "pages-gh-cli-deploy"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      actions: read     # to access the artifact of the previous workflow
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      # Step 'artifact-url' required because of:
      # - https://github.com/actions/upload-artifact/issues/50
      # - https://github.com/actions/upload-artifact/issues/382
      # simple step 'artifact-url' within one workflow doesn't work because of https://github.com/actions/upload-artifact/issues/53
      # requires multiple workflows instead https://github.com/orgs/community/discussions/51403#discussioncomment-5515349
      - name: Get artifact url
        id: artifact-url
        run: |
          previous_run_id=$(jq -r '.id' <<< "${WORKFLOW_RUN_EVENT_OBJ}")

          response=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GH_REPOSITORY}/actions/runs/${previous_run_id}/artifacts")

          artifact_url=$(jq --raw-output '.artifacts[].archive_download_url' <<< "${response}")
          echo "url=${artifact_url}" >> "$GITHUB_OUTPUT"
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
      - name: Deploy to GitHub Pages
        run: |
          gh api \
          --method POST \
          --header "Accept: application/vnd.github+json" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${GH_REPOSITORY}/pages/deployment" \
          -f artifact_url="${GH_ARTIFACT}" \
          -f environment='github-pages' \
          -f pages_build_version="${GH_SHA}" \
          -f oidc_token="${GH_TOKEN}"
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_SHA: ${{ github.sha }}
          GH_TOKEN: ${{ github.token }}
          GH_ARTIFACT: ${{ steps.artifact-url.outputs.url }}
